version: '3.8'

services:
  db:
    image: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 'password123'
      POSTGRES_USER: 'bishalgautam'
  node_server:
    build:
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: 'password123'
      POSTGRES_USER: 'bishalgautam'
    restart: unless-stopped
    # expose:
    #   - '3000'
    depends_on:
      - db
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node_server




# For Swarm
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    # deploy:
    #   replicas: 2
    #   restart_policy:
    #     max_attempts: 3
    #     condition: on-failure
    #   update_config:
    #     parallelism: 3
    #     delay: 10s


    #   proxy:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    # image: nginx_proxy:v1
    # ports:
    #   - 80:80
    # depends_on:
    #   - nodeapp
    # deploy:
    #   placement:
    #     constraints: [node.role == manager]
    # depends_on:
    #   - server
